In [1]:
import numpy as np
import pandas as pd

from statsmodels.formula.api import ols

# Не показывать FutureWarnings
import warnings
warnings.simplefilter(action='ignore', category=Warning)

In [3]:
# импорт данных
df = pd.read_csv('sleep75.csv')
df

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
0,32,0,1,0.000000,0.000000,12,0,0,1,3529,...,0,3438,0,3438,0,14,0,13,7.070004,1024
1,31,0,2,0.000000,0.000000,14,9500,1,1,2140,...,0,5020,0,5020,0,11,0,0,1.429999,961
2,44,0,3,0.000000,0.000000,17,42500,1,1,4595,...,1,2815,0,2815,0,21,0,0,20.529997,1936
3,30,0,4,0.000000,0.000000,12,42500,1,1,3211,...,1,3786,0,3786,0,12,0,12,9.619998,900
4,64,0,5,0.000000,0.000000,14,2500,1,1,4052,...,1,2580,0,2580,0,44,0,33,2.750000,4096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,45,0,702,0.182331,0.030075,12,5500,1,0,5069,...,1,2026,0,2026,0,27,0,18,NaN,2025
702,34,0,703,0.182331,0.030075,10,2500,0,0,5885,...,0,675,1,465,210,18,0,4,NaN,1156
703,37,0,704,0.182331,0.030075,12,3500,1,0,4719,...,1,1851,0,1851,0,19,0,17,NaN,1369
704,54,0,705,0.182331,0.030075,17,32500,1,0,5149,...,1,1961,1,1481,480,31,0,22,NaN,2916
705,30,0,706,0.182331,0.030075,16,6750,1,0,4747,...,0,2363,0,2363,0,8,1,9,NaN,900

In [4]:
# спецификация модели через формулу
mod = ols(formula='sleep~1+totwrk+age+smsa', data=df)
# подгонка модели
res = mod.fit()

In [5]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept    3498.67
totwrk         -0.15
age             3.00
smsa          -73.50
dtype: float64

In [6]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2150, 1950, 2240], 'age': [37, 26, 28], 'smsa': [1, 0, 1] })
new_data

   totwrk  age  smsa
0    2150   37     1
1    1950   26     0
2    2240   28     1

In [8]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)
#np.exp(res.predict(exog=new_data, transform=True))

0    3212.70
1    3283.31
2    3172.18
dtype: float64

In [9]:
#1
# спецификация модели через формулу
mod = ols(formula='sleep~1+totwrk+age+south+male+smsa+yngkid+marr', data=df)
# подгонка модели
res = mod.fit()

In [10]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2150, 1950, 2240], 'age': [37, 28, 26],'south':[0,1,0], 'male': [1,1,0], 'smsa': [1, 0, 1], 'yngkid': [0,1,0], 'marr':[1,0,0] })
new_data

   totwrk  age  south  male  smsa  yngkid  marr
0    2150   37      0     1     1       0     1
1    1950   28      1     1     0       1     0
2    2240   26      0     0     1       0     0

In [11]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)
#np.exp(res.predict(exog=new_data, transform=True))

0    3250.68
1    3371.46
2    3086.98
dtype: float64

In [14]:
#2
# спецификация модели через формулу
mod = ols(formula='sleep~1+totwrk+age+I(age ** 2)+south+male', data=df)
# подгонка модели
res = mod.fit()

In [15]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2160, 1720, 2390], 'age': [32, 24, 44],'south':[1,0,0], 'male': [0,1,1]})
new_data

   totwrk  age  south  male
0    2160   32      1     0
1    1720   24      0     1
2    2390   44      0     1

In [16]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)
#np.exp(res.predict(exog=new_data, transform=True))

0    3278.46
1    3329.25
2    3240.11
dtype: float64

In [27]:
#3
# спецификация модели через формулу
df = pd.read_csv('wage2.csv')
df
mod = ols(formula='np.log(wage)~1+age+IQ+south+married+urban', data=df)
# подгонка модели
res = mod.fit()
res.params.round(3)

Intercept    4.974
age          0.021
IQ           0.008
south       -0.099
married      0.201
urban        0.175
dtype: float64

In [28]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'age': [36, 29, 25], 'IQ': [105, 123, 112],'south':[1,0,1], 'married': [1,1,0], 'urban':[1,0,1]})
new_data

   age   IQ  south  married  urban
0   36  105      1        1      1
1   29  123      0        1      0
2   25  112      1        0      1

In [29]:
np.exp(res.predict(exog=new_data, transform=True))

0    969.945744
1    897.931235
2    665.067280
dtype: float64

In [30]:
#4
# спецификация модели через формулу
df = pd.read_csv('wage1.csv')
df
mod = ols(formula='np.log(wage)~1+exper+I(exper ** 2)+female+married+smsa', data=df)
# подгонка модели
res = mod.fit()
res.params.round(3)

Intercept        1.250
exper            0.037
I(exper ** 2)   -0.001
female          -0.363
married          0.144
smsa             0.273
dtype: float64

In [31]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'exper': [5, 26, 38], 'female': [1, 0, 1], 'married': [1,0,1], 'smsa':[1,1,0]})
new_data

   exper  female  married  smsa
0      5       1        1     1
1     26       0        0     1
2     38       1        1     0

In [32]:
np.exp(res.predict(exog=new_data, transform=True))

0    4.345478
1    7.100789
2    3.738185
dtype: float64

In [34]:
#5
# спецификация модели через формулу
df = pd.read_csv('Labour.csv')
df
mod = ols(formula='np.log(output)~1+np.log(capital)+np.log(labour)', data=df)
# подгонка модели
res = mod.fit()
res.params.round(3)

Intercept         -1.711
np.log(capital)    0.208
np.log(labour)     0.715
dtype: float64

In [35]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'capital': [2.97, 10.45, 3.85], 'labour': [85, 60, 105]})
new_data

   capital  labour
0     2.97      85
1    10.45      60
2     3.85     105

In [36]:
np.exp(res.predict(exog=new_data, transform=True))

0    5.421154
1    5.487400
2    6.654073
dtype: float64

In [37]:
#6
# спецификация модели через формулу
df = pd.read_csv('Labour.csv')
df
mod = ols(formula='np.log(output)~1+np.log(capital)+np.log(labour)+I(np.log(capital)**2)+I(np.log(labour)**2)', data=df)
# подгонка модели
res = mod.fit()
res.params.round(3)

Intercept                 -1.304
np.log(capital)            0.183
np.log(labour)             0.515
I(np.log(capital) ** 2)    0.023
I(np.log(labour) ** 2)     0.020
dtype: float64

In [38]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'capital': [22.14, 7.32, 0.67], 'labour': [407, 197, 31]})
new_data

   capital  labour
0    22.14     407
1     7.32     197
2     0.67      31

In [39]:
np.exp(res.predict(exog=new_data, transform=True))

0    27.368321
1    11.458079
2     1.886728
dtype: float64