In [1]:
import pandas as pd
import numpy as np

from statsmodels.formula.api import ols
from statsmodels.iolib.summary2 import summary_params, summary_col # вывод результатов тестирования

from scipy.stats import t # t-распределение и критические значения

# Не показывать Warnings
import warnings
warnings.simplefilter(action='ignore', category=Warning)

In [2]:
df1 = pd.DataFrame({
    'date': ['01.06.2023', '01.07.2023', '01.08.2023', '01.09.2023', '01.10.2023', '01.11.2023', '01.12.2023',
             '01.01.2024', '01.02.2024', '01.03.2024', '01.04.2024', '01.05.2024', '01.06.2024', '01.07.2024',
             '01.08.2024', '01.09.2024', '01.10.2024', '01.11.2024', '01.12.2024', '01.01.2025', '01.02.2025',
             '01.03.2025', '01.04.2025', '01.05.2025', '01.06.2025', '01.07.2025', '01.08.2025', '01.09.2025',
             '01.10.2025', '01.11.2025', '01.12.2025', '01.01.2026', '01.02.2026', '01.03.2026', '01.04.2026'],
    'interest_rate': [7.5, 7.5, 8.5, 12, 13, 15, 15, 16, 16, 16, 16, 16, 16, 16, 18, 18, 19, 21, 21, 21, 21, 21, 21, 21, 21, 20, 18, 18, 17, 16.5, 16.5, 16, 16, 15.5, 15],
    'oblig_price': [95, 97.9, 92.98, 91.5, 88.39, 84.7, 88.17, 87.1, 86.17, 83, 79.1, 77.3, 71.47, 70.519, 68.3, 67.2, 66.6, 62.65, 64.3, 68.3, 64.67, 69, 71.47, 68.89, 69.62, 73.8, 78.925, 77.07, 72.888, 73.427, 75.07, 75.1, 73.86, 74.818, 75],
    'kurs': [80.9942, 88.3844, 91.5923, 96.3344, 98.4785, 92.0226, 88.5819, 90.4040, 89.6678, 90.8423, 92.2914, 92.0538, 90.1915, 87.2972, 85.7024, 90.0013, 93.2221, 97.0226, 107.1758, 102.2911, 97.8107, 88.2568, 85.4963, 81.4933, 79.1285, 78.5284, 80.3163, 80.4261, 82.6084, 80.9756, 77.7027, 78.7913, 77.0223, 77.1734, 81.2504],
    'infl': [5.86, 5.91, 6.00, 5.59, 6.64, 7.71, 7.98, 8.14, 8.79, 9.40, 9.88, 10.23, 10.34, 10.06, 9.92, 9.52, 8.88, 8.54, 8.63, 9.05, 9.13, 8.59, 8.30, 7.84, 7.72, 7.69, 7.44, 7.42, 7.48, 6.69, 6.00, 5.15, 4.30, 3.25, 3]
})
mod = ols(formula='oblig_price ~ interest_rate + kurs + infl', data=df1)
res = mod.fit()
res.params

Intercept        110.738443
interest_rate     -2.267218
kurs               0.029797
infl               0.136334
dtype: float64

In [3]:
# уровень значимости
sign_level = 0.05
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(2.0395134463964077)

In [5]:
summary_params(res, alpha=0.05).round(3)

                 Coef.  Std.Err.       t  P>|t|  [0.025   0.975]
Intercept      110.738    10.392  10.656  0.000  89.544  131.933
interest_rate   -2.267     0.252  -9.000  0.000  -2.781   -1.753
kurs             0.030     0.125   0.239  0.813  -0.224    0.284
infl             0.136     0.553   0.246  0.807  -0.992    1.265

In [6]:
# импорт данных
df = pd.read_csv('sleep75.csv')

In [7]:
# спецификация модели
mod = ols(formula='sleep~totwrk+age+south+male+smsa+marr+union', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# подгонка модели с робастной HC3 ковариационной матрицей
res_hc = mod.fit(cov_type='HC3')

In [8]:
# уровень значимости
sign_level = 0.05
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(1.9633684547051231)

In [9]:
summary_params(res_ols, alpha=0.05).round(3)

              Coef.  Std.Err.       t  P>|t|    [0.025    0.975]
Intercept  3441.297    78.942  43.593  0.000  3286.305  3596.290
totwrk       -0.169     0.018  -9.363  0.000    -0.204    -0.133
age           2.841     1.387   2.048  0.041     0.117     5.565
south       101.676    41.834   2.430  0.015    19.541   183.810
male         86.038    34.906   2.465  0.014    17.505   154.571
smsa        -53.925    33.156  -1.626  0.104  -119.022    11.172
marr         30.006    41.910   0.716  0.474   -52.278   112.290
union        12.440    38.096   0.327  0.744   -62.357    87.236

Значимы totwrk, age, south, male

In [10]:
summary_params(res_hc, alpha=0.05).round(3)

              Coef.  Std.Err.       t  P>|t|    [0.025    0.975]
Intercept  3441.297    88.891  38.714  0.000  3267.075  3615.520
totwrk       -0.169     0.020  -8.299  0.000    -0.209    -0.129
age           2.841     1.362   2.086  0.037     0.172     5.510
south       101.676    42.315   2.403  0.016    18.740   184.611
male         86.038    35.758   2.406  0.016    15.954   156.122
smsa        -53.925    33.372  -1.616  0.106  -119.332    11.483
marr         30.006    46.090   0.651  0.515   -60.329   120.341
union        12.440    37.277   0.334  0.739   -60.622    85.501

Значимы totwrk, age, south, male

In [11]:
# спецификация модели
mod = ols(formula='sleep~totwrk+age+south+male+smsa+marr+union+np.log(hrwage)', data=df)
# подгонка модели с ковариационной матрицей по умолчанию (неробастной)
res_ols = mod.fit()
# подгонка модели с робастной HC3 ковариационной матрицей
res_hc = mod.fit(cov_type='HC3')

In [17]:
# уровень значимости
sign_level = 0.1
# критическое значение t-распределения
t.ppf(q=1-sign_level/2, df=mod.df_resid)

np.float64(1.6477723425110435)

In [19]:
summary_params(res_ols, alpha=0.1).round(3)

                   Coef.  Std.Err.       t  P>|t|     [0.05     0.95]
Intercept       3453.355    93.371  36.985  0.000  3299.501  3607.209
totwrk            -0.159     0.021  -7.629  0.000    -0.193    -0.125
age                1.950     1.584   1.230  0.219    -0.661     4.560
south             80.244    45.216   1.775  0.077     5.737   154.750
male              41.098    43.049   0.955  0.340   -29.838   112.033
smsa             -36.093    38.206  -0.945  0.345   -99.048    26.862
marr              58.917    46.613   1.264  0.207   -17.890   135.725
union             24.479    42.948   0.570  0.569   -46.289    95.247
np.log(hrwage)    -2.590    32.197  -0.080  0.936   -55.643    50.463

Значимы totwrk, south

In [20]:
summary_params(res_hc, alpha=0.1).round(3)

                   Coef.  Std.Err.       t  P>|t|     [0.05     0.95]
Intercept       3453.355    98.213  35.162  0.000  3291.809  3614.901
totwrk            -0.159     0.025  -6.354  0.000    -0.200    -0.118
age                1.950     1.571   1.241  0.215    -0.634     4.533
south             80.244    47.401   1.693  0.090     2.276   158.212
male              41.098    42.778   0.961  0.337   -29.266   111.461
smsa             -36.093    38.580  -0.936  0.350   -99.551    27.365
marr              58.917    48.350   1.219  0.223   -20.612   138.447
union             24.479    43.006   0.569  0.569   -46.260    95.218
np.log(hrwage)    -2.590    32.992  -0.079  0.937   -56.857    51.677

Значимы totwrk, south